# HW 6 - NumPy Arrays
## 1D NumPy Arrays

In [1]:
import numpy as np

In [2]:
lst = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(lst)

In [3]:
print("Multiplied by 4:", arr * 4)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]
Mean: 24.4
Median: 23.5
Standard Deviation: 13.828955130450023


In [4]:
min_idx = np.argmin(arr)
max_idx = np.argmax(arr)
print("Index of min:", min_idx)
print("Index of max:", max_idx)

Index of min: 6
Index of max: 7


In [5]:
print("Min value:", arr[min_idx])
print("Max value:", arr[max_idx])

Min value: 4
Max value: 50


In [6]:
print("Using np.min():", np.min(arr))
print("Using np.max():", np.max(arr))

Using np.min(): 4
Using np.max(): 50


In [7]:
greater_than_20 = arr[arr > 20]
print("Values > 20:", greater_than_20)

Values > 20: [27 31 50 39 35]


## 2D NumPy Arrays

In [8]:
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

In [9]:
print("Shape:", matrix.shape)  # (3, 4)
print("Third column:", matrix[:, 2])
print("Second row:", matrix[1])
print("Doubled matrix:\n", matrix * 2)
print("Mean of each column:", np.mean(matrix, axis=0))
print("Overall mean:", np.mean(matrix))
print("Max of each row:", np.max(matrix, axis=1))
print("Min of each column:", np.min(matrix, axis=0))

Shape: (3, 4)
Third column: [17 14 19]
Second row: [ 8 21 14  3]
Doubled matrix:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
Mean of each column: [ 6.33333333 15.33333333 16.66666667  7.66666667]
Overall mean: 11.5
Max of each row: [17 21 19]
Min of each column: [ 5 12 14  3]


In [10]:
flat = matrix.flatten()
print("Flattened:", flat)
print("New shape:", flat.shape)  # (12,)

Flattened: [ 5 12 17  9  8 21 14  3  6 13 19 11]
New shape: (12,)


In [11]:
min_idx = np.argmin(flat)
max_idx = np.argmax(flat)
print("Flat min index:", min_idx)
print("Flat max index:", max_idx)

Flat min index: 7
Flat max index: 5


In [12]:
min_coords = np.unravel_index(min_idx, matrix.shape)
max_coords = np.unravel_index(max_idx, matrix.shape)
print("Min coords:", min_coords)
print("Max coords:", max_coords)

Min coords: (1, 3)
Max coords: (1, 1)


In [13]:
greater_15 = matrix[matrix > 15]
print("Values > 15:", greater_15)

Values > 15: [17 21 19]


In [14]:
sorted_matrix = np.sort(matrix, axis=1)
print("Row-sorted matrix:\n", sorted_matrix)

Row-sorted matrix:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


## Prime Star Systems

In [15]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [16]:
def filter_prime_rows(arr):
    result = []
    for row in arr:
        if any(is_prime(num) for num in row):
            result.append(row)
    return np.array(result)

In [17]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

print("Prime rows:\n", filter_prime_rows(arr))

Prime rows:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


## Let's Play Checkers

In [18]:
def empty_checkerboard():
    return np.zeros((8, 8), dtype=int)

print(empty_checkerboard())

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [19]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    for i in range(8):
        board[i, i % 2::2] = 1
    return board

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [20]:
def reverse_checkerboard():
    board = np.ones((8, 8), dtype=int)
    for i in range(8):
        board[i, i % 2::2] = 0
    return board

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## The Expanding Universe

In [21]:
def expansion(array, spaces):
    result = []
    for word in array:
        spaced = (' ' * spaces).join(list(word))
        result.append(spaced)
    return np.array(result)

In [22]:
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))  # Single space
print(expansion(universe, 2))  # Double space

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


## Second Brightest Star

In [23]:
def secondDimmest(arr):
    result = []
    for row in arr:
        sorted_row = np.sort(row)
        result.append(sorted_row[-2])
    return np.array(result)

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("Stars:\n", stars)
print("Second brightest in each row:", secondDimmest(stars))

Stars:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
Second brightest in each row: [1889 1647 1138 1863 1592]
